name: Convert TS translations to JSON

on:
  push:
    branches: [master]
    paths:
      - "*.ts"

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install TypeScript tools
        run: npm install tsx --save-dev

      - name: Generate JSON files
        run: |
          mkdir -p json
          for file in *.ts; do
            base=$(basename "$file" .ts)
            echo "Converting $file → json/${base}.json"
            npx tsx -e "import f from './$file'; import fs from 'fs'; fs.writeFileSync('./json/${base}.json', JSON.stringify(f.default ?? f, null, 2))"
          done

      - name: Commit and push generated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -B generated-json
          git add -f json/*.json
          git commit -m "Auto-generated JSON files [skip ci]"
          git push origin generated-json --force

      - name: Notify Standify app
        env:
          STANDIFY_API_URL: https://getstandify.com/api/translation/
        run: |
          COMMIT_ID=$(git rev-parse HEAD)
          echo "🔔 Sending commit ID $COMMIT_ID to Standify..."
          RESPONSE=$(curl -s -L -X POST "$STANDIFY_API_URL" \
            -H "Authorization: Bearer ${{ secrets.STANDIFY_DEPLOY_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"commit_id\": \"$COMMIT_ID\"}")
          echo "📩 Response from Standify: $RESPONSE"
