name: Notify Standify about new translations

on:
  push:
    branches:
      - master
    paths:
      - "*.json"
      - "*.ts"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Standify
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.STANDIFY_DEPLOY_KEY }}" \
            -d '{"event":"translations_updated"}' \
            https://getstandify.com/api/revalidate-translations
